<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Register</title>
</head>
<body>
<h1>Register</h1>
<form action="/signUp" method="post">
    <label>Username:</label>
    <input type="username" name="username" required="required"/>
    <br/>
    <label>Password:</label>
    <input type="password" name="password" required="required"/>
    <br/>
    <button type="submit">Register</button>
</form>
</body>
</html>